### ISSUE TITLE
See Voters after a poll has finished

### ISSUE THREAD

**Issue by Wraithstalker90** [Vexed01/Vex-Cogs#120]
### What cog is this feature request for?

ButtonPoll

### Describe the feature request in as much detail as possible

Currently the only way i found to view who voted in a poll is if it is still running, it would be nice if after the fact you can use getvoters or a different command to view who had voted for what in the poll.

**Comment by Vexed01** [comment]
Looks like I didn't put the # when mentioning this issue in 655a09e so it didn't auto close.

Anyway thanks for letting me know and this should be fixed if you run `[p]cog update`
