### ISSUE TITLE
[Buttonpoll] Setup a poll purely with commands

### ISSUE THREAD

**Issue by mrPauwHaan** [Vexed01/Vex-Cogs#122]
### What cog is this feature request for?

Buttonpoll

### Describe the feature request in as much detail as possible

If its possible to setup a poll purely with commands (without modals/buttons), then it would open up possibilities to use it with other cogs like fifo. This makes planning polls easier.

**Comment by Vexed01** [comment]
I've just added this, with an argument-based system. Use the `[p]advstartpoll` command.
