### ISSUE TITLE
Steam Server Querys

### ISSUE THREAD

**Issue by PlepperGuy** [Vexed01/Vex-Cogs#123]
### What cog is this feature request for?

Status

### Describe the feature request in as much detail as possible

For a lot of games that use steamcmd you can query them for information about player count and online status.
Valheim Server is what I'm specifically looking for, using port 2457 you can query it to get the above information. Think this would be very useful for gaming communities!

**Comment by Vexed01** [comment]
This cog is purely for getting data from [Statuspage](https://www.atlassian.com/software/statuspage), and as such I have no plans to support alternative data sources. You might want to create a free or paid bounty on the [Cog Board](https://cogboard.discord.red/c/bounties/7).

Alternatively, you might be able to use the apitools cog from flare to make requests, though it wouldn't be formatted particularly well.
