### ISSUE TITLE
Delete Start Poll button message after poll is started

### ISSUE THREAD

**Issue by joshuakohut77** [Vexed01/Vex-Cogs#124]
### What cog is this feature request for?

buttonpoll

### Describe the feature request in as much detail as possible

Suggestion to delete the Start poll button message from the bot once a poll is started. It's not important to the poll and would just add a nice cleanup so others don't try to click the button after the fact.

**Comment by Vexed01** [comment]
Yes, that seems like a good idea as the text command basically plugs into the slash command once the button is clicked, and the slash won't leave a button behind.

**Comment by Vexed01** [comment]
I've decided to grey the button out (disable) instead as otherwise leaving a command with no response looks odd.
