### ISSUE TITLE
[Feature]  WOL | An Option for Reaction Response or Disabled

### ISSUE THREAD

**Issue by Menteroth** [Vexed01/Vex-Cogs#127]
### What cog is this feature request for?

WOL

### Describe the feature request in as much detail as possible

I'm using this command as a scheduled thing and it would be nice to be able to disable the response so I don't have a new message from the command every time.

**Comment by Vexed01** [comment]
Great idea and good to see I'm not the only person using the cog! I'll add a `silentwol` command which will be identical to `wol` but all messages will go to the log instead of a Discord channel.

**Comment by Menteroth** [comment]
Awesome. Thank you for that.
