### ISSUE TITLE
[Status] Twitter uptime page unavailable

### ISSUE THREAD

**Issue by Technetium1** [Vexed01/Vex-Cogs#130]
### What cog is this bug report for?

status

### What versions are you running?

```yes please
Versions                      
                ╷         ╷         ╷              
                │ Current │ Latest  │ Up to date?  
╶───────────────┼─────────┼─────────┼─────────────╴
  This Cog      │ 2.5.7   │ 2.5.7   │ 🟢           
  Bundled Utils │ b980728 │ b980728 │ 🟢           
  Red           │ 3.5.5   │ 3.5.5   │ 🟢           
                ╵         ╵         ╵
```

### Describe the bug

Once per minute, twitter fails without backing off. It looks like there may no longer be a valid status page, else this is a temporary problem. If there's a redirect to `/inactive` it might be good to avoid futher update checks?
https://api.twitterstat.us/api

### If there's an error, paste it here

```python
`[15:33:14] WARNING  [red.vex.status.updateloop.updatechecker] Unexpected status code received from twitter_api: 401. Please report this to Vexed.`
```

**Comment by Vexed01** [comment]
Thanks for reporting. It looks like Twitter has disabled the Statuspage and I can't find a replacement. I'll add some code to handle this.
