### ISSUE TITLE
[Status] Add NVIDIA GeForce NOW Status

### ISSUE THREAD

**Issue by Jac0bDan13L** [Vexed01/Vex-Cogs#15]
# Feature request

This is probably the most self-explanatory request there can be. Add NVIDA Status service. https://status.geforcenow.com/

**Comment by Vexed01** [comment]
This will be added in the Status rewrite, #13.

**Comment by Vexed01** [comment]
Status 2.0.0 has now been released. See https://vex-cogs.readthedocs.io/en/latest/changelog.html#status-2-0-0
