### ISSUE TITLE
Check in status cog has side effects (`ctx.send()` usage)

### ISSUE THREAD

**Issue by jack1142** [Vexed01/Vex-Cogs#18]
# Bug report

The check here (perhaps some other too, I haven't looked) is sending a message:
https://github.com/Vexed01/Vex-Cogs/blob/256ece0c2627d52b6e7981680c09addfa167ac39/status/commands/statusdev_com.py#L39-L61

The command checks should NOT send messages or have any other side effects as they do not only run when the command is run, they also run on things like `[p]help`, `[p]permissions canrun`, etc.
In this specific case, you should probably switch to a command `before_invoke` hook instead.

**Comment by Vexed01** [comment]
Well... 
Thanks a lot for letting me know, I've now moved this over as you suggested.
