### ISSUE TITLE
[Status] Add "Edit" Mode

### ISSUE THREAD

**Issue by Jac0bDan13L** [Vexed01/Vex-Cogs#2]
# Feature request

This would add a mode "Edit" that edits the current message of an incident message whenever an update is posted. This would be efficient in channels along side other feeds so it doesn't spam like "All" & "Latest" would. 

Some aesthetics, It'd be cool if the color of the embed corresponded with the different types of statuses Discord uses.

Identified = Red
Monitoring = Orange or Yellow
Resolved = Green

**Comment by Vexed01** [comment]
Hey! Firstly, thanks for using my cogs and taking the time to reach out.

An edit mode has been semi planned for a while, as it's more complicated than either of the other two.

Colour coding isn't something I've thought of before, and should be pretty easy to add.

**Comment by Vexed01** [comment]
Oops, closed the wrong one...

**Comment by Vexed01** [comment]
So I've done the embed colour thing in the above commit.

I'll start working on an edit mode soonish, though it might take a bit longer as I will want to make sure that it does actually work with a real incident in progress not just with my dev commands (though if it works for one service I'll assume it works for all others).

**Comment by Vexed01** [comment]
So I've now got a working edit mode for both normal messages and webhooks (d.py 1.6 supports editing webhooks). It was actually a lot easier than I thought...

I will hopefully push soon, I do want to double check that it will actually send a real update. It it working brilliantly with the dev commands so I'm 90% sure it'll work fine.

**Comment by Vexed01** [comment]
All done now, update then you can do `[p]statusset edit mode` to start using it.
