### ISSUE TITLE
[GitHub] Rewrite for buttons

### ISSUE THREAD

**Issue by Vexed01** [Vexed01/Vex-Cogs#6]
# GitHub Rewrite

The cog will be rewritten to be focused on buttons. This will happen when I have time to make a wrapper from the buttons API or (more likely) when discord.py and then Red support buttons.

Milestones support will also be added.

The cog will be renamed to `ghissues` as I was unaware of a naming conflict with obi's cog. At the time they were unapproved and I only searched approved repos for a conflict.

**Comment by Vexed01** [comment]
This will be added when buttons are released and the cog is rewritten.

**Comment by Jacob-1999** [comment]
I don't know if you already know about the [newly released buttons api](https://discord.com/developers/docs/interactions/message-components) Discord announced in [DDevs](https://i.imgur.com/uFFUNA2.png) yesterday.

**Comment by Vexed01** [comment]
Yes, these were initially released then pulled almost immediately last month.

I have played with them a bit myself, however (unless a **good** lib becomes avalible/I have time to build something wrapping the API myself) I will wait until discord.py 2.0 is released (which will have buttons built-in and would be a lot easier to code with) and then Red supports it. See `?whynobuttons` in the main server.
