### ISSUE TITLE
[stattrack] help stattrack channels command shows user (online, dnd) as examples

### ISSUE THREAD

**Issue by Skyridr** [Vexed01/Vex-Cogs#68]
### What cog is this bug report for?

stattrack

### What versions are you running?

               Your Version    Latest version    Up to date?
-------------  --------------  ----------------  -------------
This Cog       1.7.1           1.7.1             🟢
Bundled Utils  0c6bf04         0c6bf04           🟢
Red            3.4.14          3.4.16            🔴

### Describe the bug

Just a small thing. Noticed that when you are using the help command on channels, it shows dnd / online / idle as examples. But they won't work as they are meant for users.

![image](https://user-images.githubusercontent.com/6794064/148544781-fd83477c-80cf-495f-bca3-2fc1a1c2e2f8.png)

### If there's an error, paste it here

```python
That's not a valid graph. See ~help stattrack channels for a list of valid types and some examples.
```

Also, should be enhancement.. Not a bug. Sorry about that.

**Comment by Vexed01** [comment]
Thanks.
