### ISSUE TITLE
[stattrack] Show total numbers in messages/commands, etc

### ISSUE THREAD

**Issue by Skyridr** [Vexed01/Vex-Cogs#69]
### What cog is this feature request for?

stattrack

### Describe the feature request in as much detail as possible

I love the metrics! But for some metrics, it would be quite useful to show the total amount eg, messages.

![image](https://user-images.githubusercontent.com/6794064/148545331-2be5aefc-b130-40b7-93a1-aebed1fb39df.png)

To show for example how much messages were made in a specific time period. And or for eg, commands.

**Comment by Vexed01** [comment]
Thanks for formally requesting this. I've been thinking about it myself for a while.

I can't put a timeframe on this; I'll have a go tonight but if it's not super simple it might be a while until I add this.

**Comment by Skyridr** [comment]
Take your time! I already appreciated you considered it :). Thanks!

**Comment by Vexed01** [comment]
I've added this and a few other things in `1.8.0`.
