### ISSUE TITLE
[birthdays] convert from old birthdays cog

### ISSUE THREAD

**Issue by flaree** [Vexed01/Vex-Cogs#77]
### What cog is this feature request for?

birthdays 

### Describe the feature request in as much detail as possible

Ability to convert data from Zes cog if possible

**Comment by Vexed01** [comment]
Added in a4f0eee with `[p]bdset zemigrate`
The cogs cannot be loaded at the same time as each other, but both can be installed at the same time as they have different names (`birthday` vs `birthdays`)
