### ISSUE TITLE
Status: add Wikimedia

### ISSUE THREAD

**Issue by revi** [Vexed01/Vex-Cogs#97]
### What cog is this feature request for?

status

### Describe the feature request in as much detail as possible

Hi, can you add [Wikimedia](https://www.wikimediastatus.net/) ([Official](https://wikitech.wikimedia.org/wiki/Wikimediastatus.net), Atlassian StatusPage-hosted) to the preconfigured status list?

Thanks!

**Comment by Vexed01** [comment]
Done, added in version 2.5.3 / 6c6c6a5

**Comment by revi** [comment]
Thanks! (BTW, `wikimediastatus.net`'s canonical URL includes `www.` because @ cannot be CNAME'd and thus relies on Wikimedia infrastructure to 301 to `www.` (which means if wikimedia infra is down, 301 is also down) This is pretty trivial so it can wait for next release if you feel like)
